# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0004_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='circunscripcion',
        ),
    ]
