# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 19:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
